// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:440408611895:web:5c5b9ba0f7f2db2f9433b2',
    messagingSenderId: '440408611895',
    projectId: 'qrgenerator-4136d',
    authDomain: 'qrgenerator-4136d.firebaseapp.com',
    databaseURL: 'https://qrgenerator-4136d-default-rtdb.firebaseio.com',
    storageBucket: 'qrgenerator-4136d.appspot.com',
    measurementId: 'G-KXPB5XHEVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:440408611895:android:2f24f7f110aed23a9433b2',
    messagingSenderId: '440408611895',
    projectId: 'qrgenerator-4136d',
    databaseURL: 'https://qrgenerator-4136d-default-rtdb.firebaseio.com',
    storageBucket: 'qrgenerator-4136d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:440408611895:ios:fd7936dbbe2203019433b2',
    messagingSenderId: '440408611895',
    projectId: 'qrgenerator-4136d',
    databaseURL: 'https://qrgenerator-4136d-default-rtdb.firebaseio.com',
    storageBucket: 'qrgenerator-4136d.appspot.com',
    iosClientId: '440408611895-q917cj2dqld2p0c5b4rjn60sm2ghov11.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketQrReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:440408611895:ios:fd7936dbbe2203019433b2',
    messagingSenderId: '440408611895',
    projectId: 'qrgenerator-4136d',
    databaseURL: 'https://qrgenerator-4136d-default-rtdb.firebaseio.com',
    storageBucket: 'qrgenerator-4136d.appspot.com',
    iosClientId: '440408611895-q917cj2dqld2p0c5b4rjn60sm2ghov11.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketQrReader',
  );
}
